# Generated by Django 4.2.27 on 2025-12-31 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0007_vehiclelocation_manual_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "unique_together": {("vehicle", "date")},
            },
        ),
    ]
