# Generated by Django 4.2.27 on 2026-01-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_vehiclerental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerental',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclerental',
            name='start_time',
            field=models.DateField(),
        ),
    ]
