# Generated by Django 4.2.27 on 2026-01-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_alter_vehiclerental_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclerental",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="vehiclerental",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
