# Generated by Django 4.2.27 on 2025-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
