# Generated by Django 4.2.27 on 2026-02-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userv2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userv2",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
