# Generated by Django 4.2.27 on 2025-12-31 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_vendor"),
        ("vehicles", "0002_vehicleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="accounts.vendor",
            ),
        ),
    ]
