# Generated by Django 4.2.27 on 2025-12-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_vehicle_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="extra_features",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("CAR", "Car"),
                    ("SCOOTER", "Scooter"),
                    ("MOTORBIKE", "Motorbike"),
                    ("BICYCLE", "Bicycle"),
                    ("ATV_QUAD", "ATV / Quad"),
                    ("BUGGY", "Dune Buggy"),
                    ("JET_SKI", "Jet Ski"),
                    ("BOAT", "Motor Boat"),
                    ("KAYAK", "Kayak / Canoe"),
                ],
                max_length=20,
            ),
        ),
    ]
