# Generated by Django 4.2.27 on 2025-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclelocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='manual_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
