# Generated by Django 4.2.27 on 2026-01-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_brand_category_vehicle_category_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
