# Generated by Django 4.2.27 on 2026-01-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0009_vehicle_is_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="vehicle_primary_images/"
            ),
        ),
    ]
