# Generated by Django 4.2.27 on 2026-01-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0010_vehicle_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="image",
            new_name="primary_image",
        ),
    ]
