# Generated by Django 4.2.27 on 2026-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0013_alter_vehicle_vendor_alter_vehiclereview_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("CAR", "Car"),
                    ("SCOOTER", "Scooter"),
                    ("MOTORBIKE", "Motorbike"),
                    ("BICYCLE", "Bicycle"),
                    ("ATV_QUAD", "ATV / Quad"),
                    ("BUGGY", "Dune Buggy"),
                    ("JET_SKI", "Jet Ski"),
                    ("BOAT", "Motor Boat"),
                    ("KAYAK", "Kayak / Canoe"),
                    ("YACHT", "Yacht"),
                ],
                max_length=20,
            ),
        ),
    ]
