# Generated by Django 4.2.27 on 2026-02-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_vendorv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, default=dict)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('age_restriction', models.CharField(choices=[('all', 'All Ages'), ('18+', '18+ Only'), ('21+', '21+ Only')], default='all', max_length=10)),
                ('event_languages', models.JSONField(blank=True, default=list)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('food_and_drinks_available', models.BooleanField(default=False)),
                ('is_online_streamed', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sponsorship_opportunities', models.BooleanField(default=False)),
                ('is_family_friendly', models.BooleanField(default=True)),
                ('venue_capacity', models.PositiveIntegerField()),
                ('vip_venue_capacity', models.PositiveIntegerField(default=0)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='accounts.userv2')),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
    ]
