# Generated by Django 4.2.27 on 2026-02-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendee_count',
        ),
    ]
