# Generated by Django 4.2.27 on 2026-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_attendee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vip_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
