# Generated by Django 4.2.27 on 2026-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
