# Generated by Django 4.2.27 on 2026-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vip_tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
