# Generated by Django 4.2.27 on 2026-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_vip_tickets_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
