# Generated by Django 4.2.27 on 2026-02-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userv2_is_active"),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.userv2",
            ),
        ),
    ]
